{
 "title": "E-Commerce App Usage",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": " Average Fetch Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(microservices_products_fetch_time_milliseconds_sum[2m])/rate(microservices_products_fetch_time_milliseconds_sum[2m])",
     "legendFormat": " Average Fetch Time"
    }
   ]
  },
  { "title": "Product Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Product views per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(microservices_products_viewed_total[1h])",
     "legendFormat": "Product views"
    }
   ]
  },
  {
   "title": " Total Views in Last Hour",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "increase(microservices_products_viewed_total[1h])",
     "legendFormat": "Total views"
    }
   ]
  },
  {
   "title": "Stock Reductions Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "increase(microservices_products_stock_reduced_total[60m])",
     "legendFormat": "Products Reduced Total"
    }
   ]
  }
 ]
}