{
 "title": "Frontend - User Journey",
 "tags": [
  "frontend",
  "user"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource" },
   {
    "name": "user",
    "label": "User",
    "query": "label_values(microservices_frontend_tab_switches_total, user_username)"
   }
  ]
 },
 "panels": [
  {
   "title": "Completed Checkout",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(microservices_frontend_button_clicks_total{user_username=~\"$user\", button_id=\"remove-from-cart\"}[$__range])) or vector(0)"
    }
   ]
  },
  {
   "title": "Products Added to Cart",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(microservices_frontend_button_clicks_total{user_username=~\"$user\", button_id=\"add-to-cart\"}[$__range])) or vector(0)"
    }
   ]
  },
  {
   "title": "Products Removed from Cart",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(microservices_frontend_button_clicks_total{user_username=~\"$user\", button_id=\"remove-from-cart\"}[$__range])) or vector(0)"
    }
   ]
  },
  {
   "title": "Favorite Module",
   "type": "stat",
   "description": "Module where this user spent the most time",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(1, sum by (tab_name) (max_over_time(microservices_frontend_tab_time_spent_ms_sum{user_username=~\"$user\"}[$__range])))",
     "legendFormat": "{{ tab_name }}"
    }
   ]
  },
  {
   "title": "Time Spent per Module",
   "type": "piechart",
   "description": "Where this user focused their attention",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (tab_name) (increase(microservices_frontend_tab_time_spent_ms_sum{user_username=~\"$user\"}[$__range]))",
     "legendFormat": "{{ tab_name }}"
    }
   ]
  },
  {
   "title": "Modules Visited",
   "type": "barchart",
   "description": "How many times this user visited each module",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 4 },
   "targets": [
    {
     "expr": "sort_desc(sum by (tab_to) (increase(microservices_frontend_tab_switches_total{user_username=~\"$user\"}[$__range])))",
     "legendFormat": "{{ tab_to }}"
    }
   ]
  },
  {
   "title": "Activity Timeline",
   "type": "timeseries",
   "description": "When was this user active and doing what",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 4 },
   "targets": [
    {
     "expr": "sum(rate(microservices_frontend_button_clicks_total{user_username=~\"$user\", ctx_buttonId=\"add-to-cart\"}[$__rate_interval]))",
     "legendFormat": "Add to Cart"
    },
    {
     "expr": "sum(rate(microservices_frontend_form_submits_total{user_username=~\"$user\", form_name=\"checkout\"}[$__rate_interval]))",
     "legendFormat": "Checkout"
    },
    {
     "expr": "sum(rate(microservices_frontend_tab_switches_total{user_username=~\"$user\"}[$__rate_interval]))",
     "legendFormat": "Navigation"
    }
   ]
  },
  {
   "title": "Favorite Products",
   "type": "barchart",
   "description": "Products this user added to cart most",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sort_desc(sum by (ctx_productName) (max_over_time(microservices_frontend_button_clicks_total{user_username=~\"$user\", button_id=\"add-to-cart\"}[$__range]))) > 0",
     "legendFormat": "{{ ctx_productName }}"
    }
   ]
  },
  {
   "title": "Products Removed",
   "type": "barchart",
   "description": "Products this user second-guessed",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "sort_desc(sum by (ctx_productName) (increase(microservices_frontend_button_clicks_total{user_username=~\"$user\", button_id=\"remove-from-cart\"}[$__range]))) > 0",
     "legendFormat": "{{ ctx_productName }}"
    }
   ]
  },
  {
   "title": "Navigation Path",
   "type": "table",
   "description": "How this user moved through the app",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sort_desc(sum by (tab_from, tab_to) (increase(microservices_frontend_tab_switches_total{user_username=~\"$user\"}[$__range])))"
    }
   ]
  }
 ]
}